### ISSUE TITLE
No rating info shows up when multiple sentences are selected and a participant has not responded to at least one sentence

### ISSUE THREAD

**Issue by ianneidel** [kaijagahm/ygdpDashboard#43]
If multiple sentences are selected in point mode (e.g. the five hours and bakery sentence of survey 11) and a participant has not responded to at least one sentence, they will show up as a black dot. Clicking on that dot will show none of the normal rating information (e.g. not even the sentence rating they did provide). Should participants who don't have ratings for both sentences be excluded from the get-go?

Examples attached.

![Screen Shot 2021-01-04 at 5 01 11 PM](https://user-images.githubusercontent.com/68819605/103594944-f9f82f80-4eae-11eb-9421-c9e562713af2.png)
![Screen Shot 2021-01-04 at 5 01 15 PM](https://user-images.githubusercontent.com/68819605/103594946-fa90c600-4eae-11eb-8359-55a2898cb4a2.png)

**Comment by kaijagahm** [comment]
Yes, this is by design. Since we had decided to stack the sentences by AND, not OR, people who didn't rate all of the selected sentences (including people who rated none of them) are considered to not meet the criteria.

I have a separate issue logged in #37 for adding more rating info for the small black dots, and at one point we had talked about implementing more complicated boolean joins, but I haven't done it yet.
