### ISSUE TITLE
Crash on interpolation mode when trying to use survey 6 or 7

### ISSUE THREAD

**Issue by ianneidel** [kaijagahm/ygdpDashboard#45]
If we go to interpolation mode and switch to survey 6 or 7 there is a survey disconnect (every time).

**Comment by kaijagahm** [comment]
This seems to be because surveys 6 and 7 aren't included in surveySentencesTable, which is generated in the INT.R script.

This is turn is because the info for those surveys didn't make it into the SURVEY_SENTENCES table in the database.

I believe that this is now fixed for survey 7. It may not yet be fixed for survey 6. I'm re-running the code now to see what happens if we re-generate this table. I'm also going to file an issue over in the ygdpDB repo for adding this info to the database for survey 6.

**Comment by kaijagahm** [comment]
This seems to be because surveys 6 and 7 aren't represented in surveySentencesTable, which is created in INT.R.

Why aren't they in there? Seems that those surveys didn't make it into SURVEY_SENTENCES in the database.

**Comment by kaijagahm** [comment]
This is fixed, in a temporary way, for both surveys 6 and 7. Solved in https://github.com/kaijagahm/ygdpDashboard/commit/0e5ad927901582b4ee5fe233b23b0e9ee827522e
